"""Centralized prompts module for easy importing.

All prompt templates use LangChain's ChatPromptTemplate for consistent
message formatting and follow best practices from the LangChain documentation.
"""

from app.prompts.scope_prompts import (
    SCOPE_QUESTION_GENERATION_TEMPLATE,
    SCOPE_COMPLETION_DETECTION_TEMPLATE,
    SCOPE_BRIEF_GENERATION_TEMPLATE,
)

from app.prompts.report_prompts import (
    get_report_generation_prompt,
)

from app.prompts.research_prompts import (
    CREDIBILITY_HEURISTICS,
    RESEARCH_STRATEGY_SELECTION_TEMPLATE,
    RESEARCH_TASK_DECOMPOSITION_TEMPLATE,
    RESEARCH_ERROR_RE_DELEGATION_TEMPLATE,
    RESEARCH_FINDINGS_COMPRESSION_TEMPLATE,
    SUPERVISOR_GAP_ANALYSIS_TEMPLATE,
    SUPERVISOR_FINDINGS_AGGREGATION_TEMPLATE,
    SUB_AGENT_RESEARCH_TEMPLATE,
    SUB_AGENT_CITATION_EXTRACTION_TEMPLATE,
)

__all__ = [
    # Scope prompts
    "SCOPE_QUESTION_GENERATION_TEMPLATE",
    "SCOPE_COMPLETION_DETECTION_TEMPLATE",
    "SCOPE_BRIEF_GENERATION_TEMPLATE",
    # Report prompts
    "get_report_generation_prompt",
    # Research prompts
    "CREDIBILITY_HEURISTICS",
    "RESEARCH_STRATEGY_SELECTION_TEMPLATE",
    "RESEARCH_TASK_DECOMPOSITION_TEMPLATE",
    "RESEARCH_ERROR_RE_DELEGATION_TEMPLATE",
    "RESEARCH_FINDINGS_COMPRESSION_TEMPLATE",
    "SUPERVISOR_GAP_ANALYSIS_TEMPLATE",
    "SUPERVISOR_FINDINGS_AGGREGATION_TEMPLATE",
    "SUB_AGENT_RESEARCH_TEMPLATE",
    "SUB_AGENT_CITATION_EXTRACTION_TEMPLATE",
]
